/// Flutter icons FontAwesome
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontAwesome
///      fonts:
///       - asset: fonts/FontAwesome.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FontAwesome {
  FontAwesome._();

  static const _kFontFam = 'FontAwesome';

  static const IconData access_alarm = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dollar = const IconData(0xf155, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
}
